name: getx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  get: ^4.3.8

  flutter_screenutil: ^5.0.0+2

  dio: ^4.0.0
  
  shared_preferences: ^2.0.8
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  
  pull_to_refresh: ^2.0.0
  flutter_swiper_null_safety: ^1.0.0
  
  device_info_plus: ^3.0.1
  
  # gzx_dropdown_menu: ^3.1.0
  url_launcher: ^6.0.12

  # permission_handler: ^8.2.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/project.png
    - assets/icons/project_active.png
    - assets/icons/task.png
    - assets/icons/task_active.png
    - assets/icons/mine.png
    - assets/icons/mine_active.png
